const STORAGE_KEY='scorekeep-game-v1';const PEOPLE_KEY='scorekeep-people-v1';const THEME_KEY='scorekeep-theme-v1';const $=id=>document.getElementById(id);const setupView=$('setupView'),gameView=$('gameView'),winnerView=$('winnerView'),playersList=$('playersList'),savedPeopleEl=$('savedPeople'),savedPeopleGroup=$('savedPeopleGroup'),scoreInputs=$('scoreInputs'),standings=$('standings'),history=$('history'),historyCard=$('historyCard');let game=loadGame(),savedPeople=loadPeople(),editingRound=null;
function uid(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`}
function defaultGame(){return{status:'setup',players:[],roundStart:3,roundEnd:13,winMode:'low',rounds:[]}}
function migrateGame(g){if(!g)return defaultGame();if(g.roundStart==null){g.roundStart=1;g.roundEnd=g.roundCount||13}delete g.roundCount;return g}
function loadGame(){try{return migrateGame(JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultGame())}catch{return defaultGame()}}
function loadPeople(){try{const p=JSON.parse(localStorage.getItem(PEOPLE_KEY));return Array.isArray(p)?p:[]}catch{return[]}}
function saveGame(){localStorage.setItem(STORAGE_KEY,JSON.stringify(game))}function savePeople(){localStorage.setItem(PEOPLE_KEY,JSON.stringify(savedPeople))}
function applyTheme(choice){const theme=choice==='dark'?'dark':'light';document.documentElement.dataset.theme=theme;document.querySelector('meta[name="theme-color"]').setAttribute('content',theme==='dark'?'#0d1117':'#f3f4f6');document.querySelectorAll('[data-theme-choice]').forEach(b=>{const active=b.dataset.themeChoice===theme;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))})}
let themeChoice=localStorage.getItem(THEME_KEY);if(themeChoice!=='dark'&&themeChoice!=='light')themeChoice='light';applyTheme(themeChoice);document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem(THEME_KEY,b.dataset.themeChoice);applyTheme(b.dataset.themeChoice)}));
function currentPlayerNames(){return[...document.querySelectorAll('.player-name')].map(i=>i.value.trim()).filter(Boolean)}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function totalRounds(){return game.roundEnd-game.roundStart+1}function roundLabel(index){return game.roundStart+index}
function addPlayerInput(name=''){const row=document.createElement('div');row.className='player-row';row.innerHTML=`<input class="player-name" type="text" maxlength="30" placeholder="Player name" value="${escapeHtml(name)}" /><button class="remove-player" type="button" aria-label="Remove player">×</button>`;row.querySelector('.remove-player').addEventListener('click',()=>{if(playersList.children.length>2)row.remove();else row.querySelector('.player-name').value='';renderSavedPeople()});row.querySelector('.player-name').addEventListener('input',renderSavedPeople);playersList.appendChild(row);renderSavedPeople()}
function renderSavedPeople(){savedPeopleGroup.classList.toggle('hidden',savedPeople.length===0);const active=currentPlayerNames().map(n=>n.toLowerCase());savedPeopleEl.innerHTML=savedPeople.map(name=>{const added=active.includes(name.toLowerCase());return `<span class="saved-person${added?' is-added':''}"><button class="quick-add-person" type="button" data-name="${escapeHtml(name)}" ${added?'disabled':''}>${escapeHtml(name)}</button><button class="delete-person" type="button" data-name="${escapeHtml(name)}" aria-label="Delete ${escapeHtml(name)}">×</button></span>`}).join('');savedPeopleEl.querySelectorAll('.quick-add-person').forEach(b=>b.addEventListener('click',()=>{const empty=[...document.querySelectorAll('.player-name')].find(i=>!i.value.trim());if(empty){empty.value=b.dataset.name;renderSavedPeople()}else addPlayerInput(b.dataset.name)}));savedPeopleEl.querySelectorAll('.delete-person').forEach(b=>b.addEventListener('click',()=>{savedPeople=savedPeople.filter(p=>p!==b.dataset.name);savePeople();renderSavedPeople()}))}
function totals(){return game.players.map(p=>({...p,total:game.rounds.reduce((s,r)=>s+Number(r.scores[p.id]??0),0)}))}function rankedPlayers(){return totals().sort((a,b)=>game.winMode==='low'?a.total-b.total:b.total-a.total)}
function renderStandings(target=standings){target.innerHTML=rankedPlayers().map((p,i)=>`<div class="standing-row"><span class="rank">${i+1}</span><strong>${escapeHtml(p.name)}</strong><span class="total">${p.total}</span></div>`).join('')}
function renderHistory(){historyCard.classList.toggle('hidden',game.rounds.length===0);history.innerHTML=game.rounds.map((r,i)=>`<div class="history-round"><div class="history-round-head"><strong>Round ${roundLabel(i)}</strong><button class="edit-round" type="button" data-round="${i}">Edit</button></div>${game.players.map(p=>`<div class="history-row"><span>${escapeHtml(p.name)}</span><strong>${r.scores[p.id]}</strong></div>`).join('')}</div>`).join('');history.querySelectorAll('.edit-round').forEach(b=>b.addEventListener('click',()=>{editingRound=Number(b.dataset.round);renderGame();window.scrollTo({top:0,behavior:'smooth'})}))}
function renderScoreInputs(i){const editing=editingRound!==null,existing=editing?(game.rounds[i]?.scores||{}):{};scoreInputs.innerHTML=game.players.map(p=>`<label class="score-entry"><strong>${escapeHtml(p.name)}</strong><input type="number" inputmode="numeric" step="1" autocomplete="off" data-player="${p.id}" value="${editing?(existing[p.id]??''):''}" placeholder="0" aria-label="${escapeHtml(p.name)} score" /></label>`).join('')}
function fillSettings(){$('gameRoundStart').value=game.roundStart;$('gameRoundEnd').value=game.roundEnd;$('gameWinMode').value=game.winMode;$('settingsHelp').textContent=`Completed: ${game.rounds.length}. Current range: ${game.roundStart}–${game.roundEnd} (${totalRounds()} rounds).`}
function renderGame(){setupView.classList.add('hidden');winnerView.classList.add('hidden');gameView.classList.remove('hidden');const i=editingRound??game.rounds.length,label=roundLabel(i);$('roundTitle').textContent=editingRound===null?`Round ${label} of ${game.roundEnd}`:`Edit round ${label}`;$('saveRoundBtn').textContent=editingRound===null?(i+1>=totalRounds()?'Finish game':'Save round'):'Save changes';$('modeLabel').textContent=game.winMode==='low'?'Lowest wins':'Highest wins';renderScoreInputs(i);renderStandings();renderHistory();fillSettings()}
function renderWinner(){setupView.classList.add('hidden');gameView.classList.add('hidden');winnerView.classList.remove('hidden');const rank=rankedPlayers(),score=rank[0]?.total??0,winners=rank.filter(p=>p.total===score);$('winnerTitle').textContent=winners.length>1?`${winners.map(p=>p.name).join(' & ')} tie!`:`${winners[0]?.name??''} wins!`;$('winnerScore').textContent=`${score} points · ${game.winMode==='low'?'lowest':'highest'} score wins`;renderStandings($('finalStandings'))}
function renderSetup(){gameView.classList.add('hidden');winnerView.classList.add('hidden');setupView.classList.remove('hidden');playersList.innerHTML='';const names=game.players.length?game.players.map(p=>p.name):['',''];names.forEach(addPlayerInput);$('roundStart').value=game.status==='setup'?game.roundStart:3;$('roundEnd').value=game.status==='setup'?game.roundEnd:13;$('winMode').value=game.winMode||'low';renderSavedPeople()}
function render(){if(game.status==='playing')renderGame();else if(game.status==='finished')renderWinner();else renderSetup()}
$('addPlayerBtn').addEventListener('click',()=>addPlayerInput());$('savePeopleBtn').addEventListener('click',()=>{currentPlayerNames().forEach(n=>{if(!savedPeople.some(p=>p.toLowerCase()===n.toLowerCase()))savedPeople.push(n)});savePeople();renderSavedPeople()});
$('startGameBtn').addEventListener('click',()=>{const names=currentPlayerNames(),start=Number($('roundStart').value),end=Number($('roundEnd').value);if(names.length<2)return alert('Add at least two players.');if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return alert('End round must be the same as or higher than start round.');game={status:'playing',players:names.map(name=>({id:uid(),name})),roundStart:start,roundEnd:end,winMode:$('winMode').value,rounds:[]};editingRound=null;saveGame();render()});
$('saveRoundBtn').addEventListener('click',()=>{const inputs=[...scoreInputs.querySelectorAll('input[data-player]')];if(inputs.some(i=>i.value.trim()===''))return alert('Enter a score for every player.');const scores=Object.fromEntries(inputs.map(i=>[i.dataset.player,Number(i.value)]));if(editingRound!==null){game.rounds[editingRound]={scores};editingRound=null}else{game.rounds.push({scores});if(game.rounds.length>=totalRounds())game.status='finished'}saveGame();render()});
$('gameSettingsBtn').addEventListener('click',()=>{$('gameSettings').classList.toggle('hidden');fillSettings()});$('closeSettingsBtn').addEventListener('click',()=>$('gameSettings').classList.add('hidden'));
$('saveGameSettingsBtn').addEventListener('click',()=>{const start=Number($('gameRoundStart').value),end=Number($('gameRoundEnd').value);if(!Number.isFinite(start)||!Number.isFinite(end)||end<start)return alert('End round must be the same as or higher than start round.');const completed=game.rounds.length;if(end-start+1<completed)return alert(`You already have ${completed} completed rounds. The new range must contain at least ${completed} rounds.`);game.roundStart=start;game.roundEnd=end;game.winMode=$('gameWinMode').value;saveGame();$('gameSettings').classList.add('hidden');render()});
function confirmNewGame(){if(!confirm('Start a new game? Current scores will be cleared.'))return;game=defaultGame();editingRound=null;saveGame();render()}$('newGameBtn').addEventListener('click',confirmNewGame);$('freshGameBtn').addEventListener('click',confirmNewGame);$('playAgainBtn').addEventListener('click',()=>{game={...game,status:'playing',rounds:[]};editingRound=null;saveGame();render()});render();
